from app.models.script_models import ScriptRequest, ScriptResponse


class AIGeneratorService:
    async def generate_script(self, request: ScriptRequest) -> ScriptResponse:
        # TODO: Integrate with real AI backend (OpenAI/Anthropic)
        # For scaffolding, returning a template response
        
        header = ""
        if request.include_header:
            custom_text = request.custom_header_text or "Generated by ER-PSScripter"
            header = f"""<#
.SYNOPSIS
    {request.description}

.DESCRIPTION
    {request.name}
    {custom_text}

.NOTES
    Generated Date: Match 2024
#>
"""

        script_body = f"""
# Requirements: {', '.join(request.requirements)}

function Invoke-Task {{
    [CmdletBinding()]
    param()
    
    process {{
        Write-Host "Task executing..."
    }}
}}

Invoke-Task
"""
        full_content = header + script_body

        return ScriptResponse(
            name=request.name + ".ps1",
            content=full_content,
            optimization_suggestions=["Use strict mode", "Add error handling"],
            used_snippets=["Invoke-Task base"]
        )
