"""Add EntraID and MFA columns

Revision ID: 1c121ba6808b
Revises: 6bd12be6d651
Create Date: 2026-07-21 10:37:46.522461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c121ba6808b'
down_revision: Union[str, Sequence[str], None] = '6bd12be6d651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('entra_id', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('mfa_secret', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('mfa_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_user_entra_id'), 'user', ['entra_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_entra_id'), table_name='user')
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'mfa_enabled')
    op.drop_column('user', 'mfa_secret')
    op.drop_column('user', 'entra_id')
    # ### end Alembic commands ###
