"""Add_content_hash_to_snippets

Revision ID: 39b1f8c83ef4
Revises: fde04c98b945
Create Date: 2024-01-27 12:00:00.000000

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '39b1f8c83ef4'
down_revision = 'fde04c98b945'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippet', sa.Column('content_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_snippet_content_hash'), 'snippet', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snippet_content_hash'), table_name='snippet')
    op.drop_column('snippet', 'content_hash')
    # ### end Alembic commands ###
