"""Add snippet versioning

Revision ID: 6bd12be6d651
Revises: 39b1f8c83ef4
Create Date: 2026-07-21 09:06:16.562594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bd12be6d651'
down_revision: Union[str, Sequence[str], None] = '39b1f8c83ef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snippetversion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snippet_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_version_id'], ['snippetversion.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['snippet_id'], ['snippet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snippetversion_id'), 'snippetversion', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snippetversion_id'), table_name='snippetversion')
    op.drop_table('snippetversion')
    # ### end Alembic commands ###
