"""add_vector_column

Revision ID: fde04c98b945
Revises: e2e45007c81b
Create Date: 2026-01-06 10:18:05.198215

"""

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

from alembic import op

# revision identifiers, used by Alembic.
revision = 'fde04c98b945'
down_revision = 'e2e45007c81b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column('snippet', sa.Column('embedding', Vector(1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snippet', 'embedding')
    # ### end Alembic commands ###
